name: siignores
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.2
  equatable: ^2.0.3
  flutter_bloc: ^7.2.0
  internet_connection_checker: ^0.0.1+4
  flutter_screenutil: ^5.5.3+2
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  dio: ^4.0.6
  get_it: ^7.2.0
  dartz: ^0.10.1
  mask_text_input_formatter: ^2.4.0
  url_launcher: ^6.1.5
  modal_bottom_sheet: ^2.1.0
  fluttertoast: ^8.0.9
  flutter_overlay_loader: ^2.0.0
  loading_animation_widget: ^1.2.0+2
  flutter_bounce: ^1.1.0
  cached_network_image: ^3.2.1
  table_calendar: ^3.0.6
  custom_pop_up_menu: ^1.2.4
  #cache
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^5.1.0

  #Firebase
  firebase_auth: ^3.3.11
  firebase_core: ^1.11.0
  firebase_analytics: ^8.3.4
  firebase_messaging: ^11.2.5

  web_socket_channel:
  video_player:
  flick_video_player:
  flutter_keyboard_visibility:
  file_picker: ^5.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/svg/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Formular
      fonts:
        - asset: assets/fonts/Formular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Cormorant
      fonts:
        - asset: assets/fonts/Cormorant-Light.ttf
          weight: 400
  #       - asset: fonts/TrajanPro_Bold.ttf
    - family: Mak
      fonts:
        - asset: assets/fonts/MAK.otf
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy-regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
